version: '3.9'
services:
    phoenix:
        build: .
        volumes: 
            - ./src:/app
        ports:
            - "4000:4000"
        depends_on: 
            - db
    db: 
        image: postgres:13.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        volumes:
            - ./pgdata:/var/lib/postgresql/data